// Central place for enums used across models/controllers so they never drift.

const ROLES = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  WRITER: 'WRITER',
  ADMIN: 'ADMIN',
});

const WRITER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  BLOCKED: 'BLOCKED',
});

const REQUEST_STATUS = Object.freeze({
  PENDING: 'PENDING',
  MATCHED: 'MATCHED',
  QUOTATION_SENT: 'QUOTATION_SENT',
  QUOTATION_ACCEPTED: 'QUOTATION_ACCEPTED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAID: 'PAID',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
});

const QUOTATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
});

const PAYMENT_STATUS = Object.freeze({
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
});

const COMPLAINT_STATUS = Object.freeze({
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
});

const NOTIFICATION_TYPES = Object.freeze({
  REQUEST_RECEIVED: 'REQUEST_RECEIVED',
  REQUEST_ACCEPTED: 'REQUEST_ACCEPTED',
  QUOTATION_RECEIVED: 'QUOTATION_RECEIVED',
  QUOTATION_ACCEPTED: 'QUOTATION_ACCEPTED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  WORK_STARTED: 'WORK_STARTED',
  WORK_COMPLETED: 'WORK_COMPLETED',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
  NEW_MESSAGE: 'NEW_MESSAGE',
});

const WORK_TYPES = Object.freeze({
  NOTES_COPY: 'NOTES_COPY',
  FORM_FILLING: 'FORM_FILLING',
  DIAGRAM_WORK: 'DIAGRAM_WORK',
  FAIR_COPY: 'FAIR_COPY',
  DOCUMENTATION: 'DOCUMENTATION',
  OTHER: 'OTHER',
});

module.exports = {
  ROLES,
  WRITER_STATUS,
  REQUEST_STATUS,
  QUOTATION_STATUS,
  PAYMENT_STATUS,
  COMPLAINT_STATUS,
  NOTIFICATION_TYPES,
  WORK_TYPES,
};
